import { describe, expect, it } from "vitest";
import { hashOwnerPassword, isEncodedPasswordHash } from "./password";

describe("isEncodedPasswordHash", () => {
  it("accepts hashes generated by the local password utility", async () => {
    expect(
      isEncodedPasswordHash(
        await hashOwnerPassword("correct horse battery staple"),
      ),
    ).toBe(true);
  });

  it("rejects arbitrary, weak, truncated and malformed values", () => {
    expect(isEncodedPasswordHash("not-a-hash")).toBe(false);
    expect(
      isEncodedPasswordHash("pbkdf2-sha256$1000$AQID$AQID"),
    ).toBe(false);
    expect(
      isEncodedPasswordHash(
        "pbkdf2-sha256$310000$AQIDBAUGBwgJCgsMDQ4PEA$AQID",
      ),
    ).toBe(false);
  });
});
